### ISSUE TITLE
adb devices command show device offline

### ISSUE THREAD

**Issue by kaienkira** [mukul2259/experimental_device_oneplus_oneplus2#1]
everything works great, but when use use cable, adb devices command show device is offline.
adb over wlan works fine. other rom are boths ok. I dont know what's the problem is.

**Comment by kaienkira** [comment]
I'm using this rom: https://github.com/LineageOS-OP2/oneplus2_releases/releases/tag/17-10-23-test

**Comment by mukul2259** [comment]
@kaienkira Download the latest build from here https://www.pling.com/p/1386956/
